export { Header } from "./header";
export { ShowInventoryD } from "./inventory/ShowInventory";
export { InventoryD } from "./inventory/inventory";
export { PdfLayout } from "./challan/ChallanPreview";
export { CreateChallan } from "./challan/CreateChallan";
export { CustomerEdit } from "./customer/Edit";
export { CustomerCreate } from "./customer/create";
export { CustomerHome } from "./customer/index";
export { CustomerShow } from "./customer/show";
